/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f767xx.h"
#include "stm32f767xx_gpio_driver.h"
#include <stdint.h>
#include <string.h>

void delay(void) {
    for (uint32_t i = 0; i < 500000; i++)
        ;
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                                           \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
    GPIO_Handle_t GpioLedGreen, GpioBtn;
    memset(&GpioLedGreen, 0, sizeof(GpioLedGreen));
    GpioLedGreen.pGPIOx = GPIOB;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOB, ENABLE);
    GPIO_init(&GpioLedGreen);
    GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_14, GPIO_PIN_SET);

    GpioBtn.pGPIOx = GPIOD; GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
    // GpioBtn.pGPIOx = GPIOD; GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_1;
    // GpioBtn.pGPIOx = GPIOC; GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;

    GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
    GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
    // GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOD, ENABLE);
    GPIO_init(&GpioBtn);

    // IRQ Configurations
    GPIO_IRQPriorityConfig(IRQ_NO_EXTI9_5, NVIC_IRQ_PRI15); GPIO_IRQInterruptConfig(IRQ_NO_EXTI9_5, ENABLE);
    // GPIO_IRQPriorityConfig(IRQ_NO_EXTI1, NVIC_IRQ_PRI15); GPIO_IRQInterruptConfig(IRQ_NO_EXTI1, ENABLE);
    // GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, NVIC_IRQ_PRI15); GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);

    GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_0, GPIO_PIN_SET);
    while (1)
        ;
}

void EXTI9_5_IRQHandler(void) {
    // void EXTI1_IRQHandler(void) {
    // void EXTI15_10_IRQHandler(void) {

    delay();
    GPIO_IRQHandling(GPIO_PIN_NO_5);
    // GPIO_IRQHandling(GPIO_PIN_NO_1);
    // GPIO_IRQHandling(GPIO_PIN_NO_15);

    GPIO_ToggleOutputPin(GPIOB, GPIO_PIN_NO_0);
}
