/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <string.h>
#include "stm32f767xx.h"
#include "stm32f767xx_gpio_driver.h"
#include <stdint.h>

void delay(void) {
    for (uint32_t i = 0; i < 500000; i++)
        ;
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                                           \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
    GPIO_Handle_t GpioLedBlue, GpioLedGreen, GpioLedRed;
    memset(&GpioLedBlue, 0, sizeof(GpioLedBlue));
    memset(&GpioLedRed, 0, sizeof(GpioLedRed));
    memset(&GpioLedGreen, 0, sizeof(GpioLedGreen));
    GpioLedGreen.pGPIOx = GPIOB;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GpioLedGreen.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOB, ENABLE);
    GPIO_init(&GpioLedGreen);

    GpioLedBlue.pGPIOx = GPIOB;
    GpioLedBlue.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
    GpioLedBlue.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLedBlue.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLedBlue.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GpioLedBlue.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOB, ENABLE);
    GPIO_init(&GpioLedBlue);

    GpioLedRed.pGPIOx = GPIOB;
    GpioLedRed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
    GpioLedRed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GpioLedRed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLedRed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GpioLedRed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOB, ENABLE);
    GPIO_init(&GpioLedRed);

    GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_0, GPIO_PIN_SET);
    GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_7, GPIO_PIN_SET);
    GPIO_WriteToOutputPin(GPIOB, GPIO_PIN_NO_14, GPIO_PIN_SET);

    /* Loop forever */
    for (;;) {
        delay();
        GPIO_ToggleOutputPin(GPIOB, GPIO_PIN_NO_0);
        GPIO_ToggleOutputPin(GPIOB, GPIO_PIN_NO_7);
        GPIO_ToggleOutputPin(GPIOB, GPIO_PIN_NO_14);
    }
}
