/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ADC_BASE_ADDR 0x40012000UL
#define ADC_CR1_REG_OFFSET 0x04
#define ADC_CR1_REG_ADDR (ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)
#define RCC_BASE_ADDR 0x40023800UL
#define RCC_APB2_ENR_REG_OFFSET 0x44
#define RCC_APB2_ENR_REG_ADDR (RCC_BASE_ADDR + RCC_APB2_ENR_REG_OFFSET)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pRCC_APB2_ENR = (uint32_t *)RCC_APB2_ENR_REG_ADDR;
    uint32_t *pADC_CR1 = (uint32_t *)ADC_CR1_REG_ADDR;

    // Enable the ADC clock
	*pRCC_APB2_ENR |= (1 << 8);

    // Set the SCAN bit in ADC_CR1 register
    *pADC_CR1 |= (1 << 8);

    /* Loop forever */
	for(;;);
}
